name: foochly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  animate_do: ^3.3.4
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  card_swiper: ^3.0.1
  like_button: ^2.0.5
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.1.0
  simple_animations: ^5.0.2
  image_stack: ^2.1.1 
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  image: assets/images/splash.png
  color: "FFF5E0"
  fullscreen: true
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/